CREATE DATABASE EMPRESAX; 
USE EMPRESAX; 

CREATE TABLE GERENTE (
CODIGO INT AUTO_INCREMENT,
NOME VARCHAR (20),
SEXO CHAR(1),
ENDERECO VARCHAR(150),
SALARIO INT,
DEPARTAMENTO_FK INT,
PRIMARY KEY (CODIGO));

CREATE TABLE EMPREGADO( 
CODIGO INT AUTO_INCREMENT, 
NOME INT NOT NULL, 
SEXO CHAR(1), 
ENDERECO VARCHAR(150), 
SALARIO INT, 
DEPARTAMENTO_FK INT, 
SUPERVISOR_FK INT,
PRIMARY KEY(CODIGO), 
FOREIGN KEY(SUPERVISOR_FK) REFERENCES GERENTE(CODIGO) 
); 

alter table empregado
modify column nome varchar(100);
CREATE TABLE DEPENDENTE( 
EMPREGADO_FK INT, 
NOME VARCHAR(100), 
SEXO CHAR(1), 
DATANASCIMENTO DATE, 
PARENTESCO VARCHAR(50), 
PRIMARY KEY(EMPREGADO_FK), 
FOREIGN KEY(EMPREGADO_FK) REFERENCES EMPREGADO(CODIGO)); 

CREATE TABLE DEPARTAMENTO( 
NUMERO INT AUTO_INCREMENT, 
NOME VARCHAR(100), 
GERENTE_FK INT, 
DATAINICIO DATE, 
PRIMARY KEY(NUMERO), 
FOREIGN KEY(GERENTE_FK) REFERENCES GERENTE(CODIGO)); 

CREATE TABLE PROJETO( 
NUMERO INT AUTO_INCREMENT, 
NOME VARCHAR(100), 
LOCALIZACAO VARCHAR(50), 
DEPARTAMENTO_FK INT, 
PRIMARY KEY (NUMERO), 
FOREIGN KEY(DEPARTAMENTO_FK) REFERENCES DEPARTAMENTO(NUMERO));

CREATE TABLE TRABALHA( 
EMPREGADO_FK INT, 
PROJETO_FK INT, 
HORAS INT, 
PRIMARY KEY(EMPREGADO_FK), 
FOREIGN KEY (EMPREGADO_FK) REFERENCES EMPREGADO(CODIGO),
FOREIGN KEY (PROJETO_FK) REFERENCES PROJETO (NUMERO)); 

CREATE TABLE LOCALIZACAO( 
LOCALIZACAO VARCHAR(50), 
DEPARTAMENTO_FK INT, 
PRIMARY KEY (LOCALIZACAO), 
FOREIGN KEY (DEPARTAMENTO_FK) REFERENCES DEPARTAMENTO(NUMERO));


