/*PRIMEIRA QUESTÃO*/
DELIMITER //
CREATE TRIGGER DELETAR_MOVIMENTACOES AFTER DELETE ON CONTA_CORRENTE FOR EACH ROW 
BEGIN	
    DELETE FROM MOVIMENTACAO WHERE CONTA = OLD.NUMERO;
END //
DELIMITER ;


DELETE FROM CONTA_CORRENTE WHERE NUMERO = 1003;
SELECT * FROM CONTA_CORRENTE;
SELECT * FROM MOVIMENTACAO WHERE CONTA = 1003;